import ConstellationFormats
import ConstellationModel
import ConstellationTestSupport
import Testing

@testable import ConstellationGraphModel

// Deep fixture-driven verification of `RelationshipBuilder` against the real
// JS implementation (js/relationship-builder.js). Where RelationshipBuilderTests.swift
// asserts counts and a handful of spot-checked relationships, this file asserts
// EXACT SETS — every node, edge, and hull the builder produces — so any
// content-level divergence from the JS (a wrong label, a dropped filter tag, a
// mis-ordered member list) becomes a visible, specific test failure instead of
// silently passing a count check.
//
// ── Ground truth ──────────────────────────────────────────────────────────
// Expected strings below were generated by running the REAL JS builder via
// node against fixtures/comprehensive.vcf, using the same `loadBrowserClasses`
// / `VCardAdapter` helpers the JS test suite uses (test/helpers/load-app.js).
// Generator script (saved for reproducibility — rerun after any relationship-
// builder.js change to confirm the fixtures below still reflect JS behavior):
//
//   node --input-type=module -e '
//   import { loadBrowserClasses, readFixture } from
//     "/Users/nate/Developer/Constellation/test/helpers/load-app.js";
//   const { VCardAdapter, RelationshipBuilder } = loadBrowserClasses();
//   const contacts = new VCardAdapter().parse(readFixture("comprehensive.vcf"));
//   const builder = new RelationshipBuilder(contacts);
//
//   const c = (v) => (v === undefined || v === null || v === "" ? "-" : String(v));
//   const projEdges = (edges) => edges.map((e) =>
//     [c(e.source), c(e.target), c(e.type), c(e.label), c(e.reverseLabel),
//      c(e.category), c(e.inferred), c(e.edgeKind), c(e.confidence)].join("|")).sort();
//   const projNodes = (nodes) => nodes.map((n) =>
//     [c(n.id), c(n.category), c(n.isVirtual), c(n.isGroupNode),
//      (n.filterTags || []).join(",")].join("|")).sort();
//   const projHulls = (hulls) => hulls.map((h) =>
//     [c(h.id), c(h.kind), c(h.label), (h.memberIds || []).slice().sort().join(",")].join("|")).sort();
//
//   const conn = builder.build();
//   const geo = builder.build({ mode: "geographic" });
//   console.log(JSON.stringify({
//     connNodes: projNodes(conn.nodes), connEdges: projEdges(conn.edges), connHulls: projHulls(conn.hulls),
//     geoNodes: projNodes(geo.nodes), geoEdges: projEdges(geo.edges), geoHulls: projHulls(geo.hulls),
//     connStats: builder.getStats(conn.nodes, conn.edges),
//     geoStats: builder.getStats(geo.nodes, geo.edges),
//   }, null, 2));
//   '
//
// ── Options mirrored ─────────────────────────────────────────────────────
// Default connections: `builder.build()` — JS destructured defaults
// (mode: 'connections', includeInferred: true, includeLikelyFamily: true,
// includeLikelyConnections: true, includeIsolated: false, includeVirtual: true,
// rootContactId: null) — identical to `GraphBuildOptions()` on the Swift side.
// Geographic: `builder.build({ mode: 'geographic' })` — JS `_buildGeographic`
// only reads includeIsolated (default false) and rootContactId (default null,
// unused unless includeIsolated) — identical to `GraphBuildOptions(mode: .geographic)`.
//
// ── Projection format ────────────────────────────────────────────────────
//   node:  id|category|isVirtual|isGroupNode|filterTags.joined(",")
//   edge:  source|target|type|label|reverseLabel|category|inferred|edgeKind|confidence
//   hull:  id|kind|label|memberIds.sorted().joined(",")
// All lists sorted lexicographically before comparison, since neither side's
// edge/node emission order is part of the contract being verified here
// (RelationshipBuilderTests.determinismAcrossBuilds already covers ordering
// stability).
//
// ── Canonicalizations (both sides funnel through the same `c(_:)` helper) ──
//   • nil / undefined  → "-"   (JS: reverseLabel is `null` until a valid
//     reciprocal is found; edgeKind is omitted entirely on inferred org-
//     colleague edges; confidence is `undefined` on explicit/inferred-org
//     edges that never set it.)
//   • "" (empty string) → "-"  (JS emits label: '' for `contains` /
//     `located-at` geographic edges — no meaningful label exists yet the key
//     is always present; folding it into the same sentinel as "absent"
//     keeps the comparison about semantics — "is there a label" — not
//     about JS's undefined-vs-empty-string implementation detail.)
//   • Bool → "true"/"false" via Swift's `String(describing:)`, matching JS's
//     `String(true)` / `String(false)`.
//   • Double confidence → `String(Double)`, verified to match JS's
//     `String(Number)` for the two confidence constants in use (0.45, 0.38).
//
// Node/edge ids are stable hashes of the contact UID (ContactRecord.assignStableId
// / StableID.swift — both ports of the same FNV-1a/base36 algorithm), so the
// same fixture produces byte-identical ids on both sides; the sets below
// embed those hashed ids directly rather than re-deriving them per test.

private struct Fixture {
    let contacts: [Contact]

    init() {
        contacts = VCardAdapter().parse(FixtureLoader.contents(of: "comprehensive.vcf")).contacts
    }
}

// MARK: - Swift-side projection (mirrors the JS generator script above)

private func c(_ v: String?) -> String {
    guard let v, !v.isEmpty else { return "-" }
    return v
}

private func c(_ v: Bool) -> String { String(v) }

private func c(_ v: Double?) -> String {
    guard let v else { return "-" }
    return String(v)
}

private func projectNodes(_ nodes: [GraphNode]) -> [String] {
    nodes.map { n in
        [c(n.id), c(n.category), c(n.isVirtual), c(n.isGroupNode), c(n.filterTags.joined(separator: ","))]
            .joined(separator: "|")
    }.sorted()
}

private func projectEdges(_ edges: [GraphEdge]) -> [String] {
    edges.map { e in
        [
            c(e.source), c(e.target), c(e.type), c(e.label), c(e.reverseLabel),
            c(e.category), c(e.inferred), c(e.edgeKind), c(e.confidence),
        ].joined(separator: "|")
    }.sorted()
}

private func projectHulls(_ hulls: [GraphHull]) -> [String] {
    hulls.map { h in
        [c(h.id), c(h.kind), c(h.label), h.memberIds.sorted().joined(separator: ",")]
            .joined(separator: "|")
    }.sorted()
}

// MARK: - Expected sets (node-generated — see generator script above)

private let expectedConnNodes = [
    "c_1jcnyfa|other|false|false|neighbor",
    "c_3n0a4w|other|false|false|other",
    "c_4gz37t|other|false|false|other",
    "c_lutjbv|other|false|false|other",
    "c_qs7uey|other|false|false|mitre,neighbor",
    "family_group__duplicate|other|false|true|-",
    "tag_group__family|other|false|true|-",
    "tag_group__neighbor|other|false|true|-",
    "virtual__Missing_Child|virtual|true|false|virtual",
].sorted()

private let expectedConnEdges = [
    "c_lutjbv|virtual__Missing_Child|daughter|Daughter|-|family|false|explicit|-",
    "c_qs7uey|c_1jcnyfa|husband|Husband|Wife|family|false|explicit|-",
    "family_group__duplicate|c_3n0a4w|likely-surname|Duplicate|-|family|true|likely-surname|0.45",
    "family_group__duplicate|c_4gz37t|likely-surname|Duplicate|-|family|true|likely-surname|0.45",
    "tag_group__family|c_1jcnyfa|likely-tag|#family|-|other|true|likely-tag|0.38",
    "tag_group__family|c_lutjbv|likely-tag|#family|-|other|true|likely-tag|0.38",
    "tag_group__neighbor|c_1jcnyfa|likely-tag|#neighbor|-|other|true|likely-tag|0.38",
    "tag_group__neighbor|c_qs7uey|likely-tag|#neighbor|-|other|true|likely-tag|0.38",
].sorted()

private let expectedConnHulls = [
    "hull__family_group__duplicate|likely-surname|Duplicate|c_3n0a4w,c_4gz37t",
    "hull__tag_group__family|likely-tag|#family|c_1jcnyfa,c_lutjbv",
    "hull__tag_group__neighbor|likely-tag|#neighbor|c_1jcnyfa,c_qs7uey",
].sorted()

private let expectedGeoNodes = [
    "c_1hvo7vs|other|false|false|work",
    "c_1jcnyfa|other|false|false|neighbor",
    "c_qs7uey|other|false|false|mitre,neighbor",
    "geo__city__usa__ca__san-francisco|other|false|true|-",
    "geo__city__usa__va__arlington|other|false|true|-",
    "geo__country__usa|other|false|true|-",
    "geo__state__usa__ca|other|false|true|-",
    "geo__state__usa__va|other|false|true|-",
    "geo__street__usa__ca__san-francisco__market-street|other|false|true|-",
    "geo__street__usa__va__arlington__main-apt-4|other|false|true|-",
    "geo__street__usa__va__arlington__main-street|other|false|true|-",
].sorted()

private let expectedGeoEdges = [
    "geo__city__usa__ca__san-francisco|geo__street__usa__ca__san-francisco__market-street|contains|-|-|other|true|geographic-hierarchy|-",
    "geo__city__usa__va__arlington|geo__street__usa__va__arlington__main-apt-4|contains|-|-|other|true|geographic-hierarchy|-",
    "geo__city__usa__va__arlington|geo__street__usa__va__arlington__main-street|contains|-|-|other|true|geographic-hierarchy|-",
    "geo__country__usa|geo__state__usa__ca|contains|-|-|other|true|geographic-hierarchy|-",
    "geo__country__usa|geo__state__usa__va|contains|-|-|other|true|geographic-hierarchy|-",
    "geo__state__usa__ca|geo__city__usa__ca__san-francisco|contains|-|-|other|true|geographic-hierarchy|-",
    "geo__state__usa__va|geo__city__usa__va__arlington|contains|-|-|other|true|geographic-hierarchy|-",
    "geo__street__usa__ca__san-francisco__market-street|c_1hvo7vs|located-at|-|-|other|true|geographic-membership|-",
    "geo__street__usa__va__arlington__main-apt-4|c_qs7uey|located-at|-|-|other|true|geographic-membership|-",
    "geo__street__usa__va__arlington__main-street|c_1jcnyfa|located-at|-|-|other|true|geographic-membership|-",
].sorted()

private let expectedGeoHulls = [
    "hull__geo__city__usa__va__arlington|geo-city|Arlington|c_1jcnyfa,c_qs7uey",
    "hull__geo__country__usa|geo-country|USA|c_1hvo7vs,c_1jcnyfa,c_qs7uey",
    "hull__geo__state__usa__va|geo-state|VA|c_1jcnyfa,c_qs7uey",
].sorted()

// getStats(conn.nodes, conn.edges) from the JS generator run above.
private let expectedConnStats = (
    loadedContacts: 7, realContacts: 5, virtualContacts: 1, totalContacts: 6,
    realConnections: 2, virtualConnections: 6, totalConnections: 8,
    visibleNodes: 6, visibleGroups: 3, edges: 8
)

// getStats(geo.nodes, geo.edges) from the JS generator run above.
private let expectedGeoStats = (
    loadedContacts: 7, realContacts: 3, virtualContacts: 0, totalContacts: 3,
    realConnections: 0, virtualConnections: 10, totalConnections: 10,
    visibleNodes: 3, visibleGroups: 8, edges: 10
)

// MARK: - Tests

@Test func exactNodeSetMatchesJS_defaultConnections() {
    let f = Fixture()
    let model = RelationshipBuilder(f.contacts).build()
    #expect(projectNodes(model.nodes) == expectedConnNodes)
}

@Test func exactEdgeSetMatchesJS_defaultConnections() {
    let f = Fixture()
    let model = RelationshipBuilder(f.contacts).build()
    #expect(projectEdges(model.edges) == expectedConnEdges)
}

@Test func exactHullSetMatchesJS_defaultConnections() {
    let f = Fixture()
    let model = RelationshipBuilder(f.contacts).build()
    #expect(projectHulls(model.hulls) == expectedConnHulls)
}

@Test func exactNodeSetMatchesJS_geographic() {
    let f = Fixture()
    let model = RelationshipBuilder(f.contacts).build(GraphBuildOptions(mode: .geographic))
    #expect(projectNodes(model.nodes) == expectedGeoNodes)
}

@Test func exactEdgeSetMatchesJS_geographic() {
    let f = Fixture()
    let model = RelationshipBuilder(f.contacts).build(GraphBuildOptions(mode: .geographic))
    #expect(projectEdges(model.edges) == expectedGeoEdges)
}

@Test func exactHullSetMatchesJS_geographic() {
    let f = Fixture()
    let model = RelationshipBuilder(f.contacts).build(GraphBuildOptions(mode: .geographic))
    #expect(projectHulls(model.hulls) == expectedGeoHulls)
}

@Test func statsMatchJS_defaultConnections() {
    let f = Fixture()
    let builder = RelationshipBuilder(f.contacts)
    let model = builder.build()
    let stats = builder.getStats(nodes: model.nodes, edges: model.edges)

    #expect(stats.loadedContacts == expectedConnStats.loadedContacts)
    #expect(stats.realContacts == expectedConnStats.realContacts)
    #expect(stats.virtualContacts == expectedConnStats.virtualContacts)
    #expect(stats.totalContacts == expectedConnStats.totalContacts)
    #expect(stats.realConnections == expectedConnStats.realConnections)
    #expect(stats.virtualConnections == expectedConnStats.virtualConnections)
    #expect(stats.totalConnections == expectedConnStats.totalConnections)
    #expect(stats.visibleNodes == expectedConnStats.visibleNodes)
    #expect(stats.visibleGroups == expectedConnStats.visibleGroups)
    #expect(stats.edges == expectedConnStats.edges)
    #expect(stats.categories["other"] == 5)
    #expect(stats.categories["virtual"] == 1)
    #expect(stats.edgeCategories["family"] == 4)
    #expect(stats.edgeCategories["other"] == 4)
}

@Test func statsMatchJS_geographic() {
    let f = Fixture()
    let builder = RelationshipBuilder(f.contacts)
    let model = builder.build(GraphBuildOptions(mode: .geographic))
    let stats = builder.getStats(nodes: model.nodes, edges: model.edges)

    #expect(stats.loadedContacts == expectedGeoStats.loadedContacts)
    #expect(stats.realContacts == expectedGeoStats.realContacts)
    #expect(stats.virtualContacts == expectedGeoStats.virtualContacts)
    #expect(stats.totalContacts == expectedGeoStats.totalContacts)
    #expect(stats.realConnections == expectedGeoStats.realConnections)
    #expect(stats.virtualConnections == expectedGeoStats.virtualConnections)
    #expect(stats.totalConnections == expectedGeoStats.totalConnections)
    #expect(stats.visibleNodes == expectedGeoStats.visibleNodes)
    #expect(stats.visibleGroups == expectedGeoStats.visibleGroups)
    #expect(stats.edges == expectedGeoStats.edges)
    #expect(stats.categories["other"] == 3)
    #expect(stats.edgeCategories["other"] == 10)
}
