import ConstellationGraphModel
import Foundation
import Testing

/// Tick-level numeric parity between the Swift d3-force port and the real
/// vendored d3 v7 runtime.
///
/// The ground truth is generated by `scripts/physics-parity/dump-d3.cjs` from
/// the pinned graph in `scripts/physics-parity/build-graph-input.mjs`; both are
/// committed under `Tests/Goldens/physics/`. This suite replays the identical
/// simulation (same node/edge order, same force registration order, same §15.1
/// config, same restart alpha) and asserts positions/velocities match the
/// goldens bit-exactly at ticks 1, 2, 10, 100 and at alphaMin.
///
/// Parity result: **bit-exact (max abs diff 0.0)** on the target toolchain,
/// because Darwin libm agrees with V8 on every transcendental d3 uses (cos,
/// sin, pow, sqrt) — see the physics-parity README.
struct PhysicsParityTests {

    // MARK: - Golden loading

    private static let pinnedWidth = 1200.0
    private static let pinnedHeight = 800.0

    struct GraphInput: Decodable {
        struct Node: Decodable {
            let id: String
            let isGroupNode: Bool
            let groupDepth: Int?
            let isCompany: Bool
            let isVirtual: Bool
            let connectionCount: Int
            let category: String
        }
        struct Edge: Decodable {
            let id: String
            let source: String
            let target: String
            let edgeKind: String?
            let category: String
        }
        let nodes: [Node]
        let edges: [Edge]
    }

    struct Positions: Decodable {
        struct SnapNode: Decodable {
            let index: Int
            let id: String
            let x: Double
            let y: Double
            let vx: Double
            let vy: Double
        }
        struct Snapshot: Decodable {
            let label: String
            let alpha: Double
            let nodes: [SnapNode]
        }
        let alphaMin: Double
        let alphaDecay: Double
        let velocityDecay: Double
        let restTickCount: Int
        let snapshots: [Snapshot]
    }

    private static func goldensDir(_ file: String = #filePath) -> URL {
        // <repo>/macos/ConstellationKit/Tests/GraphModelTests/<this>.swift
        URL(fileURLWithPath: file)
            .deletingLastPathComponent()  // GraphModelTests
            .deletingLastPathComponent()  // Tests
            .appendingPathComponent("Goldens/physics")
    }

    private static func load<T: Decodable>(_ name: String, as: T.Type) -> T {
        let url = goldensDir().appendingPathComponent(name)
        guard let data = try? Data(contentsOf: url) else {
            fatalError("PhysicsParityTests: cannot read \(url.path)")
        }
        return try! JSONDecoder().decode(T.self, from: data)
    }

    private static func makeSimNodes(_ input: GraphInput) -> [SimNode] {
        input.nodes.map {
            SimNode(
                id: $0.id, isGroupNode: $0.isGroupNode, groupDepth: $0.groupDepth,
                isCompany: $0.isCompany, isVirtual: $0.isVirtual,
                connectionCount: $0.connectionCount, category: $0.category)
        }
    }

    private static func makeSimEdges(_ input: GraphInput) -> [SimEdge] {
        input.edges.map {
            SimEdge(
                id: $0.id, source: $0.source, target: $0.target, edgeKind: $0.edgeKind,
                category: $0.category)
        }
    }

    /// Compare the live simulation against a golden snapshot; returns the max
    /// absolute difference across x/y/vx/vy of all nodes (0.0 == bit-exact).
    private func maxDiff(_ states: [NodeState], _ snap: Positions.Snapshot) -> Double {
        #expect(states.count == snap.nodes.count)
        var maxD = 0.0
        for gold in snap.nodes {
            let s = states[gold.index]
            #expect(s.id == gold.id, "node order mismatch at index \(gold.index)")
            maxD = max(maxD, abs(s.x - gold.x))
            maxD = max(maxD, abs(s.y - gold.y))
            maxD = max(maxD, abs(s.vx - gold.vx))
            maxD = max(maxD, abs(s.vy - gold.vy))
        }
        return maxD
    }

    // MARK: - Tick-level parity (the acceptance bar)

    @Test func replaysD3TickForTickBitExact() {
        let input = Self.load("graph-input.json", as: GraphInput.self)
        let gold = Self.load("positions.json", as: Positions.self)

        // The port's alpha schedule constants must equal d3's.
        let sim = D3ForceSimulation(width: Self.pinnedWidth, height: Self.pinnedHeight)
        #expect(sim.alphaMin == gold.alphaMin)
        #expect(sim.alphaDecay == gold.alphaDecay)
        // Golden stores d3's public velocityDecay getter (1 − internal 0.6).
        #expect(1 - sim.internalVelocityDecay == gold.velocityDecay)

        sim.load(
            nodes: Self.makeSimNodes(input), edges: Self.makeSimEdges(input), incremental: false)

        // Snapshot 0 == phyllotaxis initial placement, before any tick.
        let byLabel = Dictionary(uniqueKeysWithValues: gold.snapshots.map { ($0.label, $0) })

        #expect(sim.alpha == byLabel["tick0"]!.alpha)
        #expect(maxDiff(sim.nodeStates, byLabel["tick0"]!) == 0.0, "phyllotaxis init diverged")

        var tick = 0
        for target in [1, 2, 10, 100] {
            while tick < target {
                sim.tick()
                tick += 1
            }
            let snap = byLabel["tick\(target)"]!
            #expect(sim.alpha == snap.alpha, "alpha diverged at tick \(target)")
            let d = maxDiff(sim.nodeStates, snap)
            #expect(d == 0.0, "tick \(target): max abs diff \(d) (expected bit-exact 0.0)")
        }

        // Run to rest exactly as d3's stepper does (stop after the tick that
        // drops alpha below alphaMin).
        while sim.alpha >= sim.alphaMin {
            sim.tick()
            tick += 1
        }
        #expect(tick == gold.restTickCount, "rest tick count \(tick) != \(gold.restTickCount)")
        let restSnap = byLabel["alphaMin"]!
        let restDiff = maxDiff(sim.nodeStates, restSnap)
        #expect(restDiff == 0.0, "alphaMin: max abs diff \(restDiff) (expected bit-exact 0.0)")
    }

    // MARK: - LCG stream alignment (jiggle)

    struct JiggleGolden: Decodable {
        struct Node: Decodable {
            let id: String
            let isGroupNode: Bool
            let groupDepth: Int?
            let isCompany: Bool
            let isVirtual: Bool
            let connectionCount: Int
            let category: String
            let x: Double
            let y: Double
        }
        struct Edge: Decodable {
            let id: String
            let source: String
            let target: String
            let edgeKind: String?
            let category: String
        }
        struct Scenario: Decodable {
            let nodes: [Node]
            let edges: [Edge]
        }
        let alpha: Double
        let lcgConsumptions: Int
        let scenario: Scenario
        let snapshots: [Positions.Snapshot]
    }

    /// The comprehensive-fixture layout never produces coincident points, so it
    /// never consumes the shared LCG. This scenario seeds nodes at identical
    /// positions, forcing "jiggle" in link, many-body, AND collide every tick
    /// (the golden records >0 LCG consumptions). Matching it bit-exactly proves
    /// the Swift port consumes the one shared LCG in the identical order and
    /// quantity as d3 — i.e. the streams are aligned.
    @Test func replaysJiggleScenarioBitExactProvingStreamAlignment() {
        let gold = Self.load("positions-jiggle.json", as: JiggleGolden.self)
        #expect(gold.lcgConsumptions > 0, "scenario must actually exercise the LCG")

        let nodes = gold.scenario.nodes.map {
            SimNode(
                id: $0.id, isGroupNode: $0.isGroupNode, groupDepth: $0.groupDepth,
                isCompany: $0.isCompany, isVirtual: $0.isVirtual,
                connectionCount: $0.connectionCount, category: $0.category, x: $0.x, y: $0.y)
        }
        let edges = gold.scenario.edges.map {
            SimEdge(
                id: $0.id, source: $0.source, target: $0.target, edgeKind: $0.edgeKind,
                category: $0.category)
        }

        let sim = D3ForceSimulation(width: Self.pinnedWidth, height: Self.pinnedHeight)
        sim.load(nodes: nodes, edges: edges, incremental: false)

        let byLabel = Dictionary(uniqueKeysWithValues: gold.snapshots.map { ($0.label, $0) })
        #expect(maxDiff(sim.nodeStates, byLabel["tick0"]!) == 0.0)

        var tick = 0
        for target in [1, 2, 5, 20] {
            while tick < target {
                sim.tick()
                tick += 1
            }
            let snap = byLabel["tick\(target)"]!
            #expect(sim.alpha == snap.alpha)
            let d = maxDiff(sim.nodeStates, snap)
            #expect(d == 0.0, "jiggle tick \(target): max abs diff \(d) (LCG stream misaligned?)")
        }
    }

    // MARK: - fx/fy pinning

    @Test func pinnedNodesHoldPositionWithZeroVelocity() {
        let sim = D3ForceSimulation(width: 1000, height: 1000)
        let nodes = [
            SimNode(id: "a"),
            SimNode(id: "b"),
            SimNode(id: "c"),
        ]
        let edges = [SimEdge(id: "e0", source: "a", target: "b", category: "other")]
        sim.load(nodes: nodes, edges: edges, incremental: false)

        // Pin "a" at a fixed point.
        sim.pin(id: "a", x: 123.5, y: -42.25)

        for _ in 0..<25 { sim.tick() }
        let states = Dictionary(uniqueKeysWithValues: sim.nodeStates.map { ($0.id, $0) })

        // Pinned node holds exactly and carries zero velocity (d3 semantics).
        #expect(states["a"]!.x == 123.5)
        #expect(states["a"]!.y == -42.25)
        #expect(states["a"]!.vx == 0)
        #expect(states["a"]!.vy == 0)
        #expect(states["a"]!.fx == 123.5)

        // An unpinned node has moved off its phyllotaxis origin.
        #expect(states["b"]!.x != 0 || states["b"]!.y != 0)

        // Unpin releases it (fx/fy cleared; free to move thereafter).
        sim.unpin(id: "a")
        sim.reheat(alpha: 0.3)
        let before = sim.nodeStates[0]
        for _ in 0..<10 { sim.tick() }
        let after = sim.nodeStates[0]
        #expect(after.fx == nil)
        #expect(after.x != before.x || after.y != before.y)
    }

    // MARK: - Incremental load & velocity continuity

    @Test func incrementalLoadPreservesSeededStateAndUsesAlpha03() {
        let sim = D3ForceSimulation(width: 800, height: 600)

        // Seeded nodes carry cached x/y/vx/vy — an incremental reload must keep
        // them verbatim (no phyllotaxis re-placement), preserving velocity.
        let seeded = [
            SimNode(id: "a", connectionCount: 2, x: 111.0, y: 222.0, vx: 3.5, vy: -1.25),
            SimNode(id: "b", connectionCount: 1, x: -50.0, y: 77.0, vx: 0.0, vy: 4.0),
        ]
        sim.load(nodes: seeded, edges: [], incremental: true)

        #expect(sim.alpha == ForceConfig.incrementalAlpha)
        #expect(sim.alpha == 0.3)

        let s = Dictionary(uniqueKeysWithValues: sim.nodeStates.map { ($0.id, $0) })
        #expect(s["a"]!.x == 111.0)
        #expect(s["a"]!.y == 222.0)
        #expect(s["a"]!.vx == 3.5)
        #expect(s["a"]!.vy == -1.25)
        #expect(s["b"]!.x == -50.0)
        #expect(s["b"]!.vy == 4.0)

        // A full (non-incremental) load restarts at alpha 1.0.
        let sim2 = D3ForceSimulation(width: 800, height: 600)
        sim2.load(nodes: [SimNode(id: "a")], edges: [], incremental: false)
        #expect(sim2.alpha == ForceConfig.fullLayoutAlpha)
        #expect(sim2.alpha == 1.0)
    }

    // MARK: - find(x, y, radius)

    @Test func findReturnsNearestWithinRadius() {
        let sim = D3ForceSimulation(width: 500, height: 500)
        let nodes = [
            SimNode(id: "a", x: 0, y: 0),
            SimNode(id: "b", x: 100, y: 0),
            SimNode(id: "c", x: 0, y: 100),
        ]
        // incremental so seed positions are honored exactly (no phyllotaxis).
        sim.load(nodes: nodes, edges: [], incremental: true)

        // Nearest to (95, 2) is "b".
        #expect(sim.find(x: 95, y: 2, radius: nil)?.id == "b")
        // Nearest to (3, 4) is "a".
        #expect(sim.find(x: 3, y: 4, radius: nil)?.id == "a")
        // Within a tight radius around a point far from all nodes → nil.
        #expect(sim.find(x: 300, y: 300, radius: 10) == nil)
        // Radius exactly reaching "a" from (5,0): distance 5 < radius 6 → "a".
        #expect(sim.find(x: 5, y: 0, radius: 6)?.id == "a")
        // Radius just short → nil (d3 uses strict `d2 < radius²`).
        #expect(sim.find(x: 5, y: 0, radius: 4) == nil)
    }

    // MARK: - §15.1 config table

    @Test func configTableMatchesSpec() {
        // Link distance (§15.1 rows).
        #expect(ForceConfig.linkDistance(edgeKind: "geographic-hierarchy", category: "other") == 58)
        #expect(ForceConfig.linkDistance(edgeKind: "geographic-membership", category: "other") == 70)
        #expect(ForceConfig.linkDistance(edgeKind: "likely-surname", category: "other") == 65)
        #expect(ForceConfig.linkDistance(edgeKind: "likely-tag", category: "other") == 65)
        #expect(ForceConfig.linkDistance(edgeKind: "likely-family", category: "other") == 65)
        #expect(ForceConfig.linkDistance(edgeKind: "explicit", category: "family") == 80)
        #expect(ForceConfig.linkDistance(edgeKind: "explicit", category: "work") == 100)
        #expect(ForceConfig.linkDistance(edgeKind: "explicit", category: "other") == 120)
        #expect(ForceConfig.linkDistance(edgeKind: nil, category: "other") == 120)

        // Link strength (§15.1 rows).
        #expect(ForceConfig.linkStrength(edgeKind: "geographic-hierarchy", category: "other") == 0.9)
        #expect(ForceConfig.linkStrength(edgeKind: "geographic-membership", category: "other") == 0.82)
        #expect(ForceConfig.linkStrength(edgeKind: "likely-surname", category: "other") == 0.76)
        #expect(ForceConfig.linkStrength(edgeKind: "likely-tag", category: "other") == 0.76)
        #expect(ForceConfig.linkStrength(edgeKind: "likely-family", category: "other") == 0.76)
        #expect(ForceConfig.linkStrength(edgeKind: "explicit", category: "family") == 0.4)
        #expect(ForceConfig.linkStrength(edgeKind: nil, category: "work") == 0.4)

        // Charge (§15.1 rows).
        #expect(ForceConfig.chargeStrength(isGroupNode: true, isCompany: false) == -520)
        #expect(ForceConfig.chargeStrength(isGroupNode: false, isCompany: true) == -400)
        #expect(ForceConfig.chargeStrength(isGroupNode: false, isCompany: false) == -150)
        // Group takes precedence over company.
        #expect(ForceConfig.chargeStrength(isGroupNode: true, isCompany: true) == -520)
        #expect(ForceConfig.chargeDistanceMax == 400)

        // Node radius (§15.1 rows) and collide padding.
        // Group: max(12, 18 − depth·1.5).
        #expect(
            ForceConfig.nodeRadius(
                isGroupNode: true, groupDepth: 1, isCompany: false, isVirtual: false,
                connectionCount: 0) == 16.5)
        #expect(
            ForceConfig.nodeRadius(
                isGroupNode: true, groupDepth: 5, isCompany: false, isVirtual: false,
                connectionCount: 0) == 12)  // max clamps at 12
        #expect(
            ForceConfig.nodeRadius(
                isGroupNode: true, groupDepth: nil, isCompany: false, isVirtual: false,
                connectionCount: 0) == 16.5)  // nil depth => 1
        // Company base 12 + min(cc·1.5, 10).
        #expect(
            ForceConfig.nodeRadius(
                isGroupNode: false, groupDepth: nil, isCompany: true, isVirtual: false,
                connectionCount: 2) == 15)
        // Virtual base 6.
        #expect(
            ForceConfig.nodeRadius(
                isGroupNode: false, groupDepth: nil, isCompany: false, isVirtual: true,
                connectionCount: 0) == 6)
        // Person base 10 + bonus clamps at +10.
        #expect(
            ForceConfig.nodeRadius(
                isGroupNode: false, groupDepth: nil, isCompany: false, isVirtual: false,
                connectionCount: 3) == 14.5)
        #expect(
            ForceConfig.nodeRadius(
                isGroupNode: false, groupDepth: nil, isCompany: false, isVirtual: false,
                connectionCount: 100) == 20)  // min clamps bonus at 10

        #expect(ForceConfig.collidePadding == 8)
        #expect(ForceConfig.incrementalAlpha == 0.3)
        #expect(ForceConfig.fullLayoutAlpha == 1.0)
    }
}
