import ConstellationFormats
import ConstellationModel
import ConstellationTestSupport
import Testing

@testable import ConstellationGraphModel

// Smoke-level tests for the RelationshipBuilder port. Expected counts / ids were
// generated by running the real JS builder (js/relationship-builder.js) against
// fixtures/comprehensive.vcf — see the M2 report for the generator script. A
// separate fixture-driven deep-verification task compares full node/edge/hull
// sets; these tests assert counts + a handful of known relationships.

private struct Fixture {
    let contacts: [Contact]
    let idByUID: [String: String]

    init() {
        contacts = VCardAdapter().parse(FixtureLoader.contents(of: "comprehensive.vcf")).contacts
        var map: [String: String] = [:]
        for c in contacts { if let uid = c.uid { map[uid] = c.id } }
        idByUID = map
    }

    func id(_ uid: String) -> String { idByUID[uid]! }
}

private func node(_ model: GraphModel, _ id: String) -> GraphNode? {
    model.nodes.first { $0.id == id }
}

private func edge(_ model: GraphModel, between a: String, and b: String) -> GraphEdge? {
    model.edges.first {
        ($0.source == a && $0.target == b) || ($0.source == b && $0.target == a)
    }
}

@Test func defaultConnectionsCounts() {
    let f = Fixture()
    let model = RelationshipBuilder(f.contacts).build()

    #expect(model.mode == "connections")
    #expect(model.nodes.count == 9)
    #expect(model.edges.count == 8)
    #expect(model.hulls.count == 3)

    let real = model.nodes.filter { !$0.isGroupNode && !$0.isVirtual }
    let virtual = model.nodes.filter { $0.isVirtual }
    let groups = model.nodes.filter { $0.isGroupNode }
    #expect(real.count == 5)
    #expect(virtual.count == 1)
    #expect(groups.count == 3)

    // Isolated contacts (company-acme, geo-work) are dropped by default.
    #expect(node(model, f.id("company-acme")) == nil)
    #expect(node(model, f.id("geo-work")) == nil)
}

@Test func spouseEdgeCarriesReciprocalLabels() {
    let f = Fixture()
    let model = RelationshipBuilder(f.contacts).build()

    let e = edge(model, between: f.id("jane-doe-smith"), and: f.id("john-smith"))
    #expect(e != nil)
    #expect(e?.type == "husband")
    #expect(e?.label == "Husband")
    // john lists jane back as Wife → valid husband/wife reciprocal.
    #expect(e?.reverseLabel == "Wife")
    #expect(e?.inferred == false)
    #expect(e?.edgeKind == "explicit")
    #expect(e?.category == "family")
    #expect(e?.isConfirmed == true)
}

@Test func duplicateNamesAreAmbiguousNotLinked() {
    let f = Fixture()
    let builder = RelationshipBuilder(f.contacts)

    // Two "Alex Duplicate" contacts → the name resolves to neither (ambiguous).
    #expect(builder.findContacts("Alex Duplicate").count == 2)
    #expect(builder.findContact("Alex Duplicate") == nil)

    // They share a surname cluster but no explicit edge between them.
    let model = builder.build()
    #expect(edge(model, between: f.id("duplicate-a"), and: f.id("duplicate-b")) == nil)
    #expect(node(model, "family_group__duplicate") != nil)
}

@Test func unresolvedRelationBecomesVirtualContact() {
    let f = Fixture()
    let model = RelationshipBuilder(f.contacts).build()

    let virtual = node(model, "virtual__Missing_Child")
    #expect(virtual != nil)
    #expect(virtual?.isVirtual == true)
    #expect(virtual?.category == "virtual")
    #expect(virtual?.filterTags == ["virtual"])

    // The edge from virtual-parent to the virtual child is daughter/explicit.
    let e = edge(model, between: f.id("virtual-parent"), and: "virtual__Missing_Child")
    #expect(e?.type == "daughter")
    #expect(e?.reverseLabel == nil)
}

@Test func excludeVirtualDropsUnresolvedTargets() {
    let f = Fixture()
    let model = RelationshipBuilder(f.contacts).build(
        GraphBuildOptions(includeVirtual: false))
    #expect(node(model, "virtual__Missing_Child") == nil)
}

@Test func familyNetworkHullRequiresRootContact() {
    let f = Fixture()
    let builder = RelationshipBuilder(f.contacts)

    // No "me" contact → no family-network hull.
    let noRoot = builder.build()
    #expect(noRoot.hulls.first { $0.id == "family-network" } == nil)

    // With john as "me", the connected component (john + jane) forms the hull,
    // and both nodes gain the `family` filter tag.
    let rooted = builder.build(GraphBuildOptions(rootContactId: f.id("john-smith")))
    let hull = rooted.hulls.first { $0.id == "family-network" }
    #expect(hull != nil)
    #expect(hull?.memberIds.count == 2)
    #expect(Set(hull?.memberIds ?? []) == Set([f.id("john-smith"), f.id("jane-doe-smith")]))

    #expect(node(rooted, f.id("john-smith"))?.filterTags.contains("family") == true)
    #expect(node(rooted, f.id("jane-doe-smith"))?.filterTags.contains("family") == true)
    // A non-connected real contact does not get the family tag.
    #expect(node(rooted, f.id("duplicate-a"))?.filterTags.contains("family") == false)
}

@Test func filterTagsStripLiteralFamilyHashtag() {
    let f = Fixture()
    // john's note is "#family #neighbor"; with john as root he is family-connected.
    let model = RelationshipBuilder(f.contacts).build(
        GraphBuildOptions(rootContactId: f.id("john-smith")))
    let john = node(model, f.id("john-smith"))
    // `neighbor` from the hashtag, `family` from connectivity (NOT the #family tag).
    #expect(john?.filterTags == ["neighbor", "family"])
}

@Test func noInferredNoLikelyIsExplicitOnly() {
    let f = Fixture()
    let model = RelationshipBuilder(f.contacts).build(
        GraphBuildOptions(
            includeInferred: false, includeLikelyFamily: false,
            includeLikelyConnections: false))
    #expect(model.nodes.count == 4)
    #expect(model.edges.count == 2)
    #expect(model.hulls.count == 0)
    #expect(model.nodes.allSatisfy { !$0.isGroupNode })
}

@Test func includeIsolatedKeepsUnconnectedContacts() {
    let f = Fixture()
    let model = RelationshipBuilder(f.contacts).build(
        GraphBuildOptions(includeIsolated: true))
    #expect(model.nodes.count == 11)
    #expect(model.edges.count == 8)
    #expect(node(model, f.id("company-acme")) != nil)
    #expect(node(model, f.id("company-acme"))?.category == "company")
}

@Test func geographicHierarchy() {
    let f = Fixture()
    let model = RelationshipBuilder(f.contacts).build(
        GraphBuildOptions(mode: .geographic))

    #expect(model.mode == "geographic")
    #expect(model.nodes.count == 11)
    #expect(model.edges.count == 10)
    #expect(model.hulls.count == 3)

    // Country → state → city → street hierarchy exists.
    #expect(node(model, "geo__country__usa") != nil)
    #expect(node(model, "geo__state__usa__va") != nil)
    #expect(node(model, "geo__city__usa__va__arlington") != nil)
    // Street clusters strip the leading house number.
    #expect(node(model, "geo__street__usa__va__arlington__main-street") != nil)
    #expect(node(model, "geo__street__usa__ca__san-francisco__market-street") != nil)

    // Contacts without an address are dropped unless includeIsolated.
    #expect(node(model, "geo__country__no-address") == nil)

    let usaHull = model.hulls.first { $0.id == "hull__geo__country__usa" }
    #expect(usaHull?.memberIds.count == 3)
    #expect(usaHull?.color == "#74b9ff")  // depth 1
}

@Test func geographicIncludeIsolatedAddsNoAddressGroup() {
    let f = Fixture()
    let model = RelationshipBuilder(f.contacts).build(
        GraphBuildOptions(mode: .geographic, includeIsolated: true))
    #expect(model.nodes.count == 16)
    #expect(model.edges.count == 14)
    #expect(model.hulls.count == 4)
    let noAddr = node(model, "geo__country__no-address")
    #expect(noAddr?.isGroupNode == true)
}

@Test func statsMatchJS() {
    let f = Fixture()
    let builder = RelationshipBuilder(f.contacts)
    let model = builder.build()
    let stats = builder.getStats(nodes: model.nodes, edges: model.edges)

    #expect(stats.loadedContacts == 7)
    #expect(stats.realContacts == 5)
    #expect(stats.virtualContacts == 1)
    #expect(stats.totalContacts == 6)
    #expect(stats.realConnections == 2)
    #expect(stats.virtualConnections == 6)
    #expect(stats.totalConnections == 8)
    #expect(stats.visibleNodes == 6)
    #expect(stats.visibleGroups == 3)
    #expect(stats.categories["other"] == 5)
    #expect(stats.categories["virtual"] == 1)
    #expect(stats.edgeCategories["family"] == 4)
    #expect(stats.edgeCategories["other"] == 4)
}

@Test func determinismAcrossBuilds() {
    let f = Fixture()
    let builder = RelationshipBuilder(f.contacts)
    let a = builder.build()
    let b = builder.build()
    // Node / edge / hull ordering is stable run-to-run (Equatable is order-sensitive
    // for arrays), so two builds of the same input are identical.
    #expect(a == b)
    #expect(a.nodes.map(\.id) == b.nodes.map(\.id))
    #expect(a.edges.map(\.id) == b.edges.map(\.id))
}
