// FilterEngine / sidebar-filter fidelity tests.
//
// The expected sets below are GROUND TRUTH generated by running the real JS
// `_filteredContactsForSidebar` (js/app-sidebar.js) through the Node test
// harness (test/helpers/load-app.js → makeTestApp) over fixtures/comprehensive.vcf.
// Each scenario records the ordered node ids + names the JS produced.

import ConstellationFormats
import ConstellationGraphModel
import ConstellationModel
import ConstellationTestSupport
import Testing

@testable import ConstellationStore

@MainActor
private func comprehensiveStore() -> AppStore {
    let text = FixtureLoader.contents(of: "comprehensive.vcf")
    let contacts = VCardAdapter().parse(text).contacts
    let store = AppStore()
    store.loadContacts(contacts, fileLabel: "comprehensive.vcf", activeFormatID: "vcard")
    return store
}

private func names(_ nodes: [GraphNode]) -> [String] { nodes.map(\.name) }
private func ids(_ nodes: [GraphNode]) -> [String] { nodes.map(\.id) }

// ── Ground truth: no search, no filter (first-last sort) ──────────────────────
@Test @MainActor func sidebarNoSearchNoFilter() {
    let store = comprehensiveStore()
    let list = store.filteredContacts
    #expect(ids(list) == ["c_9l17d", "c_3n0a4w", "c_4gz37t", "c_qs7uey", "c_1jcnyfa", "c_1hvo7vs", "c_lutjbv"])
    #expect(names(list) == [
        "Acme Corporation International Research and Development Holdings",
        "Alex Duplicate",
        "Alex Duplicate",
        "Dr. Jane, Q. Doe;Smith",
        "John Smith",
        "Taylor Geo",
        "Virtual Parent",
    ])
    // Virtual + group nodes are excluded from the sidebar list.
    #expect(!list.contains { $0.isVirtual || $0.isGroupNode })
}

// ── Search over the five list fields ──────────────────────────────────────────
@Test @MainActor func sidebarSearchMatchesNameAndOrg() {
    let store = comprehensiveStore()
    store.searchText = "smith"
    #expect(ids(store.filteredContacts) == ["c_qs7uey", "c_1jcnyfa"])
}

@Test @MainActor func sidebarSearchIsCaseInsensitive() {
    let store = comprehensiveStore()
    store.searchText = "SMITH"
    #expect(ids(store.filteredContacts) == ["c_qs7uey", "c_1jcnyfa"])
}

@Test @MainActor func sidebarSearchMatchesNotesHashtag() {
    // Only Acme carries "#vendor" in its notes.
    let store = comprehensiveStore()
    store.searchText = "#vendor"
    #expect(ids(store.filteredContacts) == ["c_9l17d"])
}

@Test @MainActor func sidebarEmptySearchIsNoOp() {
    let store = comprehensiveStore()
    store.searchText = ""
    #expect(store.filteredContacts.count == 7)
}

// ── Filter tags: OR semantics ─────────────────────────────────────────────────
@Test @MainActor func sidebarFilterCompany() {
    let store = comprehensiveStore()
    store.setActiveFilters(["company"])
    #expect(ids(store.filteredContacts) == ["c_9l17d"])
}

@Test @MainActor func sidebarFilterCompanyOrVirtualIsUnion() {
    // "virtual" adds no *real* sidebar nodes, so the union equals company alone.
    let store = comprehensiveStore()
    store.setActiveFilters(["company", "virtual"])
    #expect(ids(store.filteredContacts) == ["c_9l17d"])
}

@Test @MainActor func sidebarFilterOther() {
    let store = comprehensiveStore()
    store.setActiveFilters(["other"])
    #expect(ids(store.filteredContacts) == ["c_3n0a4w", "c_4gz37t", "c_lutjbv"])
}

// ── Search + filter combine (AND across the two stages) ───────────────────────
@Test @MainActor func sidebarSearchAndFilterCombine() {
    let store = comprehensiveStore()
    store.searchText = "inc"
    store.setActiveFilters(["company"])
    #expect(store.filteredContacts.isEmpty)
}

// ── My Family filter (requires a "me") ────────────────────────────────────────
@Test @MainActor func sidebarFamilyFilterWithSelf() {
    let store = comprehensiveStore()
    store.setSelfContact("c_qs7uey")  // Dr. Jane Doe-Smith
    #expect(store.toggleFilter("family") == true)
    #expect(ids(store.filteredContacts) == ["c_qs7uey", "c_1jcnyfa"])
}

@Test @MainActor func familyFilterIgnoredWithoutSelf() {
    let store = comprehensiveStore()
    #expect(store.selfContactID == nil)
    // Toggling family is a no-op while no "me" is chosen (JS button guard).
    #expect(store.toggleFilter("family") == false)
    #expect(store.activeFilterTags.isEmpty)
}

// ── Category list (system + sorted dynamic) ───────────────────────────────────
@Test @MainActor func availableCategoriesAreSystemThenSortedDynamic() {
    let store = comprehensiveStore()
    // System tags always lead in fixed order; dynamic hashtags follow, sorted.
    #expect(Array(store.allCategories.prefix(4)) == ["family", "company", "virtual", "other"])
    let dynamic = Array(store.allCategories.dropFirst(4))
    #expect(dynamic == dynamic.sorted())
    #expect(dynamic.contains("mitre"))
    #expect(dynamic.contains("neighbor"))
    #expect(dynamic.contains("vendor"))
    #expect(dynamic.contains("work"))
    #expect(!dynamic.contains("family"))  // literal "family" hashtag is stripped
}

// ── Sort mode: last-first reorders by family name ─────────────────────────────
@Test @MainActor func lastFirstSortReordersByFamily() {
    let store = comprehensiveStore()
    store.contactSortMode = .lastFirst
    // "Smith, John" now sorts under S; ordering differs from first-last.
    let firstLast = comprehensiveStore()
    #expect(ids(store.filteredContacts) != ids(firstLast.filteredContacts))
    // John Smith's structured family is "Smith" → sort key begins "smith".
    let key = FilterEngine.sortKey(store.nodeById["c_1jcnyfa"]!, sortMode: .lastFirst)
    #expect(key.hasPrefix("smith"))
}

// ── FilterEngine name formatting (unit) ───────────────────────────────────────
@Test func formatListNameLastFirst() {
    let n = StructuredName(family: "Smith", given: "John", prefix: "Dr.")
    #expect(FilterEngine.formatListName(fn: "John Smith", structured: n, mode: .lastFirst) == "Smith, Dr. John")
    #expect(FilterEngine.formatListName(fn: "John Smith", structured: n, mode: .firstLast) == "John Smith")
}

@Test func formatListNameFallsBackWithoutFamily() {
    let n = StructuredName(given: "Cher")
    // No family ⇒ last-first falls back to the display name.
    #expect(FilterEngine.formatListName(fn: "Cher", structured: n, mode: .lastFirst) == "Cher")
}

@Test func composeDisplayNameOrdersParts() {
    let n = StructuredName(family: "Doe", given: "Jane", additional: "Q.", prefix: "Dr.", suffix: "PhD")
    #expect(FilterEngine.composeDisplayName(n) == "Dr. Jane Q. Doe PhD")
}
