import ConstellationModel
import ConstellationTestSupport
import CryptoKit
import Foundation
import Testing

@testable import ConstellationFormats

/// Byte-identity proof against the Node reference implementation.
///
/// Expected SHA-256 hashes and UTF-8 byte counts were generated by running the
/// JS modules directly (node --input-type=module, js/vcf-parser.js /
/// js/vcard-serializer.js / js/vcard-adapter.js) over the shared fixtures:
///   1. `ser` — VCardAdapter.serialize straight after parse (raw passthrough)
///   2. `rew` — rewriteVCard applied to every contact, then serialize
///   3. `gen` — rawVCard cleared, generateVCard per contact, joined with "\n"
/// A hash match means the Swift port produces byte-identical output.
@Suite struct VCardByteParityTests {
    private func sha256(_ s: String) -> String {
        SHA256.hash(data: Data(s.utf8)).map { String(format: "%02x", $0) }.joined()
    }

    private func pipeline(_ fixture: String) -> (ser: String, rew: String, gen: String) {
        let text = FixtureLoader.contents(of: fixture)
        var contacts = VCFParser().parse(text)
        let adapter = VCardAdapter()
        let ser = adapter.serialize(contacts, ids: nil)
        for i in contacts.indices {
            contacts[i].rawVCard = VCardSerializer.rewriteVCard(contacts[i])
        }
        let rew = adapter.serialize(contacts, ids: nil)
        for i in contacts.indices {
            contacts[i].rawVCard = nil
        }
        let gen = contacts.map { VCardSerializer.generateVCard($0) }.joined(separator: "\n")
        return (ser, rew, gen)
    }

    private func dumpOnMismatch(_ label: String, _ got: String) {
        let dir = FileManager.default.temporaryDirectory
        let url = dir.appendingPathComponent("constellation-parity-\(label).txt")
        try? got.write(to: url, atomically: true, encoding: .utf8)
    }

    @Test func comprehensiveFixtureIsByteIdenticalWithNode() {
        let out = pipeline("comprehensive.vcf")
        #expect(out.ser.utf8.count == 1896)
        if sha256(out.ser) != "3f2850374f188d3a431ee1ab86215601f3692455b18d7fe510feb03fd2e0dd05" {
            dumpOnMismatch("comprehensive-ser", out.ser)
        }
        #expect(
            sha256(out.ser)
                == "3f2850374f188d3a431ee1ab86215601f3692455b18d7fe510feb03fd2e0dd05")

        #expect(out.rew.utf8.count == 1967)
        if sha256(out.rew) != "0bf01143049fe6f01d84a01054a569dcee8004f2a3c7019b50b0dab6e9a32cc1" {
            dumpOnMismatch("comprehensive-rew", out.rew)
        }
        #expect(
            sha256(out.rew)
                == "0bf01143049fe6f01d84a01054a569dcee8004f2a3c7019b50b0dab6e9a32cc1")

        #expect(out.gen.utf8.count == 1964)
        if sha256(out.gen) != "47e3e4e3bf34c0211b4ca56ad621c23971da9ff2603b8bc58c52f5ade8a87275" {
            dumpOnMismatch("comprehensive-gen", out.gen)
        }
        #expect(
            sha256(out.gen)
                == "47e3e4e3bf34c0211b4ca56ad621c23971da9ff2603b8bc58c52f5ade8a87275")
    }

    @Test func appleTortureFixtureIsByteIdenticalWithNode() {
        let out = pipeline("apple-full-fields.vcf")
        #expect(out.ser.utf8.count == 28953)
        if sha256(out.ser) != "fccdc4d20bf248584b8bad0cbb1ca1a44b5bd90ca8e941ef7e98e0c4cf212b9b" {
            dumpOnMismatch("apple-ser", out.ser)
        }
        #expect(
            sha256(out.ser)
                == "fccdc4d20bf248584b8bad0cbb1ca1a44b5bd90ca8e941ef7e98e0c4cf212b9b")

        #expect(out.rew.utf8.count == 28943)
        if sha256(out.rew) != "c554d026a985124e9085ada5181604f1d098a0d0e293fcbf02ab79c034fb3512" {
            dumpOnMismatch("apple-rew", out.rew)
        }
        #expect(
            sha256(out.rew)
                == "c554d026a985124e9085ada5181604f1d098a0d0e293fcbf02ab79c034fb3512")

        #expect(out.gen.utf8.count == 28208)
        if sha256(out.gen) != "d4eec5b98975cf4ea3a61c236676e3cd0bf9b1b51e3c6659e6be53cc559cc1c6" {
            dumpOnMismatch("apple-gen", out.gen)
        }
        #expect(
            sha256(out.gen)
                == "d4eec5b98975cf4ea3a61c236676e3cd0bf9b1b51e3c6659e6be53cc559cc1c6")
    }
}
